### ISSUE TITLE
convert to python 3

### ISSUE THREAD

**Issue by biojet1** [hogesonline/svg_play#5]
```
 python 'a_bit_mondrian.py'
<svg viewBox="0 0 500 500" xmlns="http://www.w3.org/2000/svg">

Traceback (most recent call last):
  File "a_bit_mondrian.py", line 37, in <module>
    draw_mondrian(500, 500, COLORNUMS)
  File "a_bit_mondrian.py", line 18, in draw_mondrian
    col = random.choice(colors)
  File "/usr/lib/python3.6/random.py", line 261, in choice
    return seq[i]
TypeError: 'dict_keys' object does not support indexing
```

**Comment by ruckyboy** [comment]
Change line 14 to: 
    colors = list(color_nums.keys())
